<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ZoneUrbaine extends \App\Entities\ZoneUrbaine implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'batiments' => [parent::class, 'batiments', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nbArbresExist' => [parent::class, 'nbArbresExist', null, 16],
        "\0".parent::class."\0".'niveauPollution' => [parent::class, 'niveauPollution', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'population' => [parent::class, 'population', null, 16],
        "\0".parent::class."\0".'surface' => [parent::class, 'surface', null, 16],
        'batiments' => [parent::class, 'batiments', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nbArbresExist' => [parent::class, 'nbArbresExist', null, 16],
        'niveauPollution' => [parent::class, 'niveauPollution', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'population' => [parent::class, 'population', null, 16],
        'surface' => [parent::class, 'surface', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
