<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Batiment extends \App\Entities\Batiment implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'emissionCO2' => [parent::class, 'emissionCO2', null, 16],
        "\0".parent::class."\0".'emissionReelle' => [parent::class, 'emissionReelle', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nbEmployes' => [parent::class, 'nbEmployes', null, 16],
        "\0".parent::class."\0".'nbHabitants' => [parent::class, 'nbHabitants', null, 16],
        "\0".parent::class."\0".'pourcentageRenouvelable' => [parent::class, 'pourcentageRenouvelable', null, 16],
        "\0".parent::class."\0".'typeIndustrie' => [parent::class, 'typeIndustrie', null, 16],
        "\0".parent::class."\0".'type_batiment' => [parent::class, 'type_batiment', null, 16],
        "\0".parent::class."\0".'zone' => [parent::class, 'zone', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'emissionCO2' => [parent::class, 'emissionCO2', null, 16],
        'emissionReelle' => [parent::class, 'emissionReelle', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nbEmployes' => [parent::class, 'nbEmployes', null, 16],
        'nbHabitants' => [parent::class, 'nbHabitants', null, 16],
        'pourcentageRenouvelable' => [parent::class, 'pourcentageRenouvelable', null, 16],
        'typeIndustrie' => [parent::class, 'typeIndustrie', null, 16],
        'type_batiment' => [parent::class, 'type_batiment', null, 16],
        'zone' => [parent::class, 'zone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
